### ISSUE TITLE
Scrappy does not reply/DM me when I post to scrapbook (neither does @hakkuun)

### ISSUE THREAD

**Issue by polytroper** [hackclub/scrapbook#784]
I don't get a reply or a DM from Scrapbook when I post. It does post to my scrapbook, and I get the emoji reactions on the post. But no messages from `@scrappy` or `@hakkuun`. This happens consistently on every scrapbook post, both in #scrapbook and on posts made with the emoji, for me and at least one other user (Dillon Barnes, `@dil`)

https://hackclub.slack.com/archives/C02AWNTDXUH/p1719241881568379
https://hackclub.slack.com/archives/C05SVRTCDGV/p1719076134435689

**Comment by polytroper** [comment]
For anyone who was tagged here, I do apologize, these @ tags are for bots/users in our slack channel.

**Comment by JosiasAurel** [comment]
ok after some digging it seems that this issue only affects admin users 

here are the logs related to one of your posts

```

2024-06-24 15:11:36.663 [scrappy_hackclub] web.1                                 ^
2024-06-24 15:11:36.663 [scrappy_hackclub] web.1
2024-06-24 15:11:36.663 [scrappy_hackclub] web.1 Error: An API error occurred: cannot_update_admin_user
2024-06-24 15:11:36.663 [scrappy_hackclub] web.1     at platformErrorFromResult (/app/node_modules/@slack/web-api/dist/errors.js:62:33)
2024-06-24 15:11:36.663 [scrappy_hackclub] web.1     at WebClient.apiCall (/app/node_modules/@slack/web-api/dist/WebClient.js:181:56)
2024-06-24 15:11:36.663 [scrappy_hackclub] web.1     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
2024-06-24 15:11:36.663 [scrappy_hackclub] web.1   code: 'slack_webapi_platform_error',
2024-06-24 15:11:36.663 [scrappy_hackclub] web.1   data: {
```
